"""Tests for the receipt cleaner.

Every vendor sample used here is synthetic, generated by
``tests/fixtures/make_fixture.make_vendor_samples``. Nothing in this file
reaches the network: the one test that exercises downloading replaces
``clean.urlopen``, and two tests assert that the offline paths would explode if
they tried to open a socket.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

import clean
import pytest
from fixtures.make_fixture import make_vendor_samples

VENDORS_DIR = Path(__file__).resolve().parents[1] / "vendors"
VENDOR_NAMES = ["doordash", "lyft", "plaintext", "uber", "united"]


def sample_path(vendor: str) -> Path:
    suffix = "sample.txt" if vendor == "plaintext" else "sample.html"
    return VENDORS_DIR / vendor / suffix


@pytest.fixture(scope="module")
def rules() -> dict[str, dict]:
    return clean.load_vendor_rules(VENDORS_DIR)


@pytest.fixture(scope="module")
def samples() -> dict[str, str]:
    return {name: sample_path(name).read_text(encoding="utf-8") for name in VENDOR_NAMES}


@pytest.fixture
def no_network(monkeypatch: pytest.MonkeyPatch) -> None:
    """Make any download attempt fail loudly rather than quietly succeed."""

    def explode(*args: object, **kwargs: object) -> None:
        raise AssertionError("this code path must not open the network")

    monkeypatch.setattr(clean, "urlopen", explode)


# ------------------------------------------------------------- generic clean


def test_scripts_are_removed(no_network: None) -> None:
    raw = "<html><body><p>Fare</p><script>track()</script><script src='x.js'></body></html>"
    out = clean.clean_html(raw)
    assert "script" not in out.lower()
    assert "track()" not in out
    assert "<p>Fare</p>" in out


def test_wrapper_and_head_are_removed() -> None:
    raw = (
        "<!DOCTYPE html><html lang='en'><head><title>Receipt</title>"
        "<meta charset='utf-8'><link rel='stylesheet' href='v.css'></head>"
        "<body bgcolor='#fff'><p>Total</p></body></html>"
    )
    out = clean.clean_html(raw)
    assert out == "<p>Total</p>"


def test_body_without_wrapper_survives() -> None:
    assert clean.clean_html("<p>Just a fragment</p>") == "<p>Just a fragment</p>"


def test_empty_input_is_empty_output() -> None:
    assert clean.clean_html("") == ""
    assert clean.clean_html(None) == ""


def test_meta_and_link_outside_head_are_removed() -> None:
    raw = "<body><meta name='x' content='y'><link rel='next' href='z'><p>Keep</p></body>"
    assert clean.clean_html(raw) == "<p>Keep</p>"


def test_html_comments_are_removed() -> None:
    raw = "<body><!-- [if mso]> junk <![endif] --><p>Keep</p></body>"
    assert clean.clean_html(raw) == "<p>Keep</p>"


# ---------------------------------------------------------------- css scoping


def test_style_blocks_are_kept_and_scoped() -> None:
    raw = (
        "<html><head><style>\n"
        "body{margin:0;background:#fff}\n"
        "html,body{padding:0}\n"
        ".foo{color:red}\n"
        ".foo, .bar td{font-size:14px}\n"
        "body.dark{color:#fff}\n"
        "</style></head><body><p class='foo'>Fare</p></body></html>"
    )
    out = clean.clean_html(raw)
    assert "<style>" in out
    assert ".rc{margin:0;background:#fff}" in out
    assert ".rc, .rc{padding:0}" in out
    assert ".rc .foo{color:red}" in out
    assert ".rc .foo, .rc .bar td{font-size:14px}" in out
    assert ".rc.dark{color:#fff}" in out
    assert "body{" not in out


def test_at_rules_keep_their_wrapper_and_scope_what_is_inside() -> None:
    css = (
        "@media print{body{margin:0}.foo{display:none}}"
        "@font-face{font-family:Vendor;src:url(v.woff2)}"
        "@import url(other.css);"
        "/* a comment */"
        "@keyframes spin{from{opacity:0}to{opacity:1}}"
    )
    out = clean.clean_html(f"<style>{css}</style><p>x</p>")
    assert "@media print{.rc{margin:0}.rc .foo{display:none}}" in out
    assert "@font-face{font-family:Vendor;src:url(v.woff2)}" in out
    assert "@import url(other.css);" in out
    assert "/* a comment */" in out
    assert "@keyframes spin{from{opacity:0}to{opacity:1}}" in out


def test_css_comments_and_unterminated_blocks_do_not_break_scoping() -> None:
    css = ".a{color:red/* } not a brace */}\n.b{color:blue"
    out = clean.clean_html(f"<style>{css}</style>")
    assert ".rc .a{color:red/* } not a brace */}" in out
    assert ".rc .b{color:blue}" in out


def test_css_without_any_rule_is_passed_through() -> None:
    assert clean._scope_css("") == ""
    assert clean._scope_css("  \n ") == "  \n "
    assert clean._scope_css("{color:red}") == "{color:red}"


def test_empty_style_block_emits_no_style_tag() -> None:
    assert clean.clean_html("<style>   </style><p>x</p>") == "<p>x</p>"


# -------------------------------------------------------------- tracking pixels


@pytest.mark.parametrize(
    "tag",
    [
        '<img src="https://example.com/a.gif" width="1" height="1">',
        '<img src="https://example.com/a.gif" height="1">',
        '<img src="https://example.com/o/open?id=9" width="600">',
        '<img src="https://example.com/t/track/9" width="600">',
        '<img src="https://example.com/pixel.gif" width="600">',
        '<img src="https://example.com/beacon" width="600">',
        '<img src="https://example.com/a.gif" style="width:1px;height:1px">',
    ],
)
def test_tracking_pixels_are_removed(tag: str) -> None:
    assert clean.clean_html(f"<body>{tag}<p>Keep</p></body>") == "<p>Keep</p>"


def test_real_images_survive() -> None:
    tag = '<img src="https://cdn.example.com/logo.png" width="34" height="34" alt="Vendor">'
    assert tag in clean.clean_html(f"<body>{tag}</body>")


def test_a_data_uri_logo_is_never_read_as_a_pixel() -> None:
    # The letters of the pixel hints can turn up inside base64 by chance, so the
    # hint test must apply to http sources only.
    tag = '<img src="data:image/png;base64,AAopenAAtrackAApixelAA" width="34" height="34">'
    assert tag in clean.clean_html(f"<body>{tag}</body>")


def test_attribute_lookup_ignores_lookalike_attributes() -> None:
    tag = '<img data-width="1" src="https://cdn.example.com/logo.png" width="90">'
    assert tag in clean.clean_html(tag)
    assert clean._attr(tag, "width") == "90"
    assert clean._attr(tag, "alt") is None


def test_attribute_lookup_handles_every_quoting_style() -> None:
    assert clean._attr("<img width='12'>", "width") == "12"
    assert clean._attr("<img width=12>", "width") == "12"


# ----------------------------------------------------------------- vendor strip


def test_lyft_strip_removes_the_promo_block(rules: dict, samples: dict) -> None:
    raw = samples["lyft"]
    assert "ride pass" in raw
    out = clean.clean_html(raw, rules["lyft"])
    assert "ride pass" not in out
    assert "Add a tip" not in out
    # The fare table, including the tip line and the total, is untouched.
    assert "Lyft fare" in out
    assert "Airport fee" in out
    assert ">Tip</td>" in out
    assert ">Total</td>" in out
    assert "Thanks for riding with" in out


def test_doordash_strip_removes_the_track_button_and_footer(rules: dict, samples: dict) -> None:
    raw = samples["doordash"]
    assert "Track your order" in raw
    out = clean.clean_html(raw, rules["doordash"])
    assert "Track your order" not in out
    assert "Unsubscribe" not in out
    assert "Subtotal" in out
    assert "Dasher tip" in out
    assert "Cedar Street Noodle Bar" in out


def test_doordash_strip_handles_the_nested_button_shape(rules: dict) -> None:
    raw = (
        "<table><tr><td><table><tr><td>"
        '<div class="button" id="Red100"><a style="color:#fff">Track Your Order</a></div>'
        "</td></tr></table></td></tr></table>"
    )
    out = clean.clean_html(raw, rules["doordash"])
    assert "Track Your Order" not in out
    assert "<table>" in out


def test_doordash_strip_removes_the_hero_image_row(rules: dict) -> None:
    raw = (
        "<table><tr><td><p>Keep this</p></td></tr>"
        '<tr><td align="center"><a><img alt src="https://img.example.com/x-hero-img-2x.png">'
        "</a></td></tr></table>"
    )
    out = clean.clean_html(raw, rules["doordash"])
    assert "hero" not in out
    assert "Keep this" in out


@pytest.mark.parametrize("vendor", ["lyft", "doordash"])
def test_at_least_one_strip_pattern_matches_the_sample(
    vendor: str, rules: dict, samples: dict
) -> None:
    patterns = rules[vendor]["strip_regex"]
    assert any(re.search(p, samples[vendor], re.S) for p in patterns)


@pytest.mark.parametrize("vendor", VENDOR_NAMES)
def test_every_strip_pattern_compiles(vendor: str, rules: dict) -> None:
    for pattern in rules[vendor]["strip_regex"]:
        re.compile(pattern, re.S)


# ----------------------------------------------------------------------- links


def test_tracking_anchors_are_unwrapped_to_plain_text(rules: dict) -> None:
    raw = (
        '<p><a href="https://click.example.com/x">See passes</a> and '
        '<a href="https://example.com/track/9">Open the app</a> and '
        '<a href="https://example.com/help?utm_source=email">Get help</a> and '
        '<a href="https://example.com/policy">Policy</a></p>'
    )
    out = clean.clean_html(raw, rules["lyft"])
    assert "See passes and" in out
    assert "Open the app" in out
    assert "Get help" in out
    assert out.count("<a") == 1
    assert ">Policy</a>" in out


def test_remaining_anchors_keep_styling_but_carry_no_href() -> None:
    raw = (
        '<a href="https://example.com/x" target="_blank" rel="noopener" '
        'onclick="go()" style="color:#ff00bf" class="cta">Policy</a>'
    )
    out = clean.clean_html(raw)
    assert "href" not in out
    assert "target" not in out
    assert "onclick" not in out
    assert 'style="color:#ff00bf"' in out
    assert 'class="cta"' in out
    assert ">Policy</a>" in out


def test_an_anchor_with_no_attributes_survives() -> None:
    assert clean.clean_html("<a>Plain</a>") == "<a>Plain</a>"


def test_unwrap_is_skipped_when_a_vendor_names_no_patterns() -> None:
    rules = {"unwrap_links_matching": []}
    out = clean.clean_html('<a href="https://click.example.com/x">Text</a>', rules)
    assert out == "<a>Text</a>"


# ---------------------------------------------------------------------- images


def test_inline_images_replaces_only_what_is_cached(tmp_path: Path, no_network: None) -> None:
    cached = "https://cdn.example.com/logo.png"
    missing = "https://cdn.example.com/other.png"
    empty = "https://cdn.example.com/empty.jpg"
    (tmp_path / clean.cache_name(cached)).write_bytes(b"\x89PNG-ish")
    (tmp_path / clean.cache_name(empty)).write_bytes(b"")
    html = f'<img src="{cached}"><img src="{missing}"><img src=\'{empty}\'>'
    out = clean.inline_images(html, tmp_path)
    assert 'src="data:image/png;base64,' in out
    assert f'src="{missing}"' in out
    assert f"src='{empty}'" in out


def test_inline_images_guesses_the_mime_type_past_a_query_string(
    tmp_path: Path, no_network: None
) -> None:
    url = "https://cdn.example.com/logo.gif?v=3&s=2x"
    (tmp_path / clean.cache_name(url)).write_bytes(b"GIF89a")
    out = clean.inline_images(f'<img src="{url}">', tmp_path)
    assert "data:image/gif;base64,R0lGODlh" in out


def test_inline_images_leaves_data_uris_alone(tmp_path: Path, no_network: None) -> None:
    html = '<img src="data:image/png;base64,AAAA">'
    assert clean.inline_images(html, tmp_path) == html


def test_clean_html_inlines_when_a_cache_is_given(tmp_path: Path, no_network: None) -> None:
    url = "https://cdn.example.com/logo.png"
    (tmp_path / clean.cache_name(url)).write_bytes(b"bytes")
    out = clean.clean_html(f'<body><img src="{url}" width="34"></body>', None, tmp_path)
    assert "data:image/png;base64,Ynl0ZXM=" in out


def test_cache_name_is_the_sha256_prefix() -> None:
    name = clean.cache_name("https://cdn.example.com/logo.png")
    assert len(name) == 16
    assert re.fullmatch(r"[0-9a-f]{16}", name)


class _FakeResponse:
    def __init__(self, blob: bytes) -> None:
        self._blob = blob

    def __enter__(self) -> _FakeResponse:
        return self

    def __exit__(self, *exc: object) -> bool:
        return False

    def read(self) -> bytes:
        return self._blob


def test_fetch_images_downloads_into_the_cache(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    wanted = "https://cdn.example.com/logo.png"
    already = "https://cdn.example.com/cached.png"
    blank = "https://cdn.example.com/blank.png"
    broken = "https://cdn.example.com/broken.png"
    cache = tmp_path / "images"
    cache.mkdir()
    (cache / clean.cache_name(already)).write_bytes(b"old")

    calls: list[str] = []

    def fake_urlopen(url: str, timeout: int = 0) -> _FakeResponse:
        calls.append(url)
        assert timeout == clean.FETCH_TIMEOUT
        if url == broken:
            raise OSError("no route")
        return _FakeResponse(b"" if url == blank else b"new bytes")

    monkeypatch.setattr(clean, "urlopen", fake_urlopen)
    html = "".join(f'<img src="{url}">' for url in (wanted, wanted, already, blank, broken))
    assert clean.fetch_images(html, cache) == 1
    assert calls == [wanted, blank, broken]
    assert (cache / clean.cache_name(wanted)).read_bytes() == b"new bytes"
    assert (cache / clean.cache_name(already)).read_bytes() == b"old"
    assert not (cache / clean.cache_name(blank)).exists()


# ----------------------------------------------------------------------- rules


def test_load_vendor_rules_reads_every_vendor(rules: dict) -> None:
    assert sorted(rules) == VENDOR_NAMES
    for name, rule in rules.items():
        assert rule["name"] == name
        assert isinstance(rule["notes"], str) and rule["notes"]
        assert rule["amount_regex"] and rule["date_regex"]


def test_load_vendor_rules_keeps_the_rules_as_plain_data(rules: dict) -> None:
    for rule in rules.values():
        for key in clean.LIST_KEYS:
            assert all(isinstance(item, str) for item in rule[key])


def test_load_vendor_rules_rejects_a_missing_key(tmp_path: Path) -> None:
    body = json.loads((VENDORS_DIR / "lyft" / "rules.json").read_text(encoding="utf-8"))
    del body["amount_regex"]
    target = tmp_path / "lyft"
    target.mkdir()
    (target / "rules.json").write_text(json.dumps(body), encoding="utf-8")
    with pytest.raises(ValueError, match="missing key amount_regex"):
        clean.load_vendor_rules(tmp_path)


def test_load_vendor_rules_rejects_a_key_of_the_wrong_shape(tmp_path: Path) -> None:
    body = json.loads((VENDORS_DIR / "lyft" / "rules.json").read_text(encoding="utf-8"))
    body["sender_domains"] = "lyft.com"
    body["name"] = 7
    target = tmp_path / "lyft"
    target.mkdir()
    (target / "rules.json").write_text(json.dumps(body), encoding="utf-8")
    with pytest.raises(ValueError, match="sender_domains must be a list"):
        clean.load_vendor_rules(tmp_path)


def test_load_vendor_rules_rejects_a_file_that_is_not_an_object(tmp_path: Path) -> None:
    target = tmp_path / "odd"
    target.mkdir()
    (target / "rules.json").write_text("[1, 2]", encoding="utf-8")
    with pytest.raises(ValueError, match="must hold a JSON object"):
        clean.load_vendor_rules(tmp_path)


def test_load_vendor_rules_on_an_empty_directory(tmp_path: Path) -> None:
    assert clean.load_vendor_rules(tmp_path) == {}


# ------------------------------------------------------------- vendor detection


@pytest.mark.parametrize(
    ("from_addr", "expected"),
    [
        ("no-reply@lyftmail.com", "lyft"),
        ("Lyft <no-reply@LYFTMAIL.COM>", "lyft"),
        ("receipts@mail.lyft.com", "lyft"),
        ("no-reply@doordash.com", "doordash"),
        ("unitedairlines@united.com", "united"),
        ("noreply@uber.com", "uber"),
    ],
)
def test_detect_vendor_by_sender_domain(from_addr: str, expected: str, rules: dict) -> None:
    assert clean.detect_vendor(from_addr, "", rules) == expected


@pytest.mark.parametrize(
    ("subject", "expected"),
    [
        ("Your ride with Teodoro", "lyft"),
        ("Your Cedar Street Noodle Bar order", "doordash"),
        ("eTicket Itinerary and Receipt", "united"),
        ("United Wi-Fi receipt", "united"),
        ("Your Uber receipt", "uber"),
        ("Your Harborview Hotel stay is confirmed", "plaintext"),
        ("Reservation for your stay", "plaintext"),
    ],
)
def test_detect_vendor_by_subject(subject: str, expected: str, rules: dict) -> None:
    assert clean.detect_vendor("someone@example.org", subject, rules) == expected


@pytest.mark.parametrize(
    ("from_addr", "subject"),
    [
        ("someone@example.org", "Weekly update"),
        ("someone@notlyft.com", "Weekly update"),
        ("", ""),
        ("not-an-address", "Weekly update"),
        (None, None),
    ],
)
def test_detect_vendor_returns_none(from_addr: str, subject: str, rules: dict) -> None:
    assert clean.detect_vendor(from_addr, subject, rules) is None


def test_a_catch_all_never_beats_a_vendor_with_a_domain(rules: dict) -> None:
    # The subject matches plaintext too, but doordash is tried first.
    assert clean.detect_vendor("", "Your dinner order confirmation", rules) == "doordash"


def test_the_sender_domain_wins_over_the_subject(rules: dict) -> None:
    assert clean.detect_vendor("x@uber.com", "eTicket Itinerary and Receipt", rules) == "uber"


def test_sender_domains_may_be_written_with_an_at_sign(rules: dict) -> None:
    loose = {"loose": dict(rules["lyft"], name="loose", sender_domains=["@lyft.com", " "])}
    assert clean.detect_vendor("x@lyft.com", "", loose) == "loose"


# --------------------------------------------------------------- vendor samples


@pytest.mark.parametrize("vendor", VENDOR_NAMES)
def test_amount_and_date_patterns_match_the_sample(vendor: str, rules: dict, samples: dict) -> None:
    rule = rules[vendor]
    amount = re.search(rule["amount_regex"], samples[vendor], re.S)
    date = re.search(rule["date_regex"], samples[vendor], re.S)
    assert amount, f"{vendor} amount_regex found nothing"
    assert date, f"{vendor} date_regex found nothing"
    assert re.fullmatch(r"-?\$[\d,]+\.\d{2}", amount.group(1))
    assert re.search(r"\d{4}", date.group(1))


def test_samples_are_exactly_what_the_generator_produces(tmp_path: Path) -> None:
    make_vendor_samples(tmp_path)
    produced = {
        "lyft": "lyft.html",
        "doordash": "doordash.html",
        "united": "united.html",
        "uber": "uber.html",
        "plaintext": "plaintext.txt",
    }
    for vendor, name in produced.items():
        assert (
            sample_path(vendor).read_bytes() == (tmp_path / name).read_bytes()
        ), f"vendors/{vendor} sample has drifted from make_vendor_samples"


@pytest.mark.parametrize("vendor", VENDOR_NAMES)
def test_no_sample_cleans_down_to_a_live_link(vendor: str, rules: dict, samples: dict) -> None:
    out = clean.clean_html(samples[vendor], rules[vendor])
    assert "href" not in out
    assert "http://" not in out
    assert "https://" not in out


def test_a_generic_clean_keeps_the_values_but_drops_the_links(samples: dict) -> None:
    out = clean.clean_html(samples["lyft"])
    assert "$28.93" in out
    assert "ride pass" in out  # no vendor rules, so the promo row stays
    assert "href" not in out
    assert "See passes" in out


# ------------------------------------------------------------------------- cli


def test_cli_cleans_the_lyft_sample(tmp_path: Path, no_network: None) -> None:
    source = tmp_path / "in.html"
    shutil.copyfile(sample_path("lyft"), source)
    out = tmp_path / "out" / "clean.html"
    code = clean.main(
        [
            str(source),
            "--out",
            str(out),
            "--vendor",
            "lyft",
            "--vendors",
            str(VENDORS_DIR),
        ]
    )
    assert code == 0
    written = out.read_text(encoding="utf-8")
    assert "$28.93" in written
    assert ">Total</td>" in written
    assert "<script" not in written
    assert "ride pass" not in written
    assert "href" not in written


def test_cli_without_a_vendor_is_the_generic_clean(tmp_path: Path) -> None:
    source = tmp_path / "in.html"
    source.write_text("<html><body><p>Fare</p></body></html>", encoding="utf-8")
    out = tmp_path / "out.html"
    assert clean.main([str(source), "--out", str(out)]) == 0
    assert out.read_text(encoding="utf-8") == "<p>Fare</p>\n"


def test_cli_rejects_an_unknown_vendor(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    source = tmp_path / "in.html"
    source.write_text("<p>x</p>", encoding="utf-8")
    code = clean.main(
        [
            str(source),
            "--out",
            str(tmp_path / "o.html"),
            "--vendor",
            "hertz",
            "--vendors",
            str(VENDORS_DIR),
        ]
    )
    assert code == 2
    assert "no rules for vendor hertz" in capsys.readouterr().err


def test_cli_refuses_to_fetch_without_a_cache(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    source = tmp_path / "in.html"
    source.write_text("<p>x</p>", encoding="utf-8")
    code = clean.main([str(source), "--out", str(tmp_path / "o.html"), "--fetch-images"])
    assert code == 2
    assert "needs --images" in capsys.readouterr().err


def test_cli_fetches_then_inlines(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    url = "https://cdn.example.com/logo.png"
    source = tmp_path / "in.html"
    source.write_text(f'<body><img src="{url}" width="34"></body>', encoding="utf-8")
    monkeypatch.setattr(clean, "urlopen", lambda *a, **k: _FakeResponse(b"bytes"))
    out = tmp_path / "o.html"
    code = clean.main(
        [
            str(source),
            "--out",
            str(out),
            "--images",
            str(tmp_path / "images"),
            "--fetch-images",
        ]
    )
    assert code == 0
    assert "data:image/png;base64,Ynl0ZXM=" in out.read_text(encoding="utf-8")


def test_cli_writes_next_to_the_working_directory(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)
    Path("in.html").write_text("<p>Fare</p>", encoding="utf-8")
    assert clean.main(["in.html", "--out", "out.html"]) == 0
    assert Path("out.html").read_text(encoding="utf-8") == "<p>Fare</p>\n"
